### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by neo125874** [ugiacoman/react-native-broadcast#2]
usage in the readme, what's the scenario about this lib?  could you explain more or screenshot step by step?

thanks

**Comment by ugiacoman** [comment]
If you need to stream to youtube from a mobile device and are using react-native, this lib is for you.

**Comment by primayudantra** [comment]
how can i put my streamkey? can you give me the example? @ugiacoman

**Comment by ugiacoman** [comment]
@primayudantra Sure, the stream key is really just part of the rtmp url. 

For Example:
Server URL: `rtmp://a.rtmp.youtube.com/live2`
Stream key: `hs21-3abs-7290-10mz`

Would be: `rtmpUrl: rtmp://a.rtmp.youtube.com/live2/hs21-3abs-7290-10mz`

I'm planning on making an example project soon. Hopefully this should solve some confusion.

**Comment by primayudantra** [comment]
Thanks for your reply! @ugiacoman 
I'll try it.
