### ISSUE TITLE
npm install Error 

### ISSUE THREAD

**Issue by BenLakes** [ugiacoman/react-native-broadcast#4]
npm install react-native-broadcast --save
npm ERR! code E404
npm ERR! 404 Not Found: react-native-broadcast@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cavs/.npm/_logs/2017-09-26T13_57_35_862Z-debug.log

**Comment by nguyenanhthai** [comment]
same here

**Comment by nmhung** [comment]
I can not install, too

**Comment by zjjne** [comment]
I can not install, too

**Comment by ugiacoman** [comment]
Hey guys, sorry for the late reply! Never actually released this on npm! Since I am no longer maintaining this repo, I don't have plans to release on npm. You'll have to install it locally.
