### ISSUE TITLE
setParameters failed

### ISSUE THREAD

**Issue by callmejm** [ugiacoman/react-native-broadcast#5]
First Thank for this library, and second there are an error when I try to set the width and height value from width 1280 height 720 to , width 720 height 1280.

` this.mPublisher.setPreviewResolution(720, 1280);`
` this.mPublisher.setOutputResolution(720, 1280);`

in  `RNBroadcastViewManager.java` method `createViewInstance` , I rebuild in Android Studio is no problem, when I build in react-native , i get the error `setParameters failed`.

**Comment by ugiacoman** [comment]
Hey @JayricMok, I'm no longer actively maintaining this repo. Unfortunately, I am not sure why you are getting this error.
